import { createContext, useContext, useMemo, useState } from 'react';

export const LanguageContext = createContext(null);

export const languages = [
  { code: 'ru', label: 'RU' },
  { code: 'uk', label: 'UA' },
  { code: 'en', label: 'EN' }
];

export const translations = {
  ru: {
    appSubtitle: 'Fitness MVP',
    navDashboard: 'Dashboard',
    navMeasurements: 'Замеры',
    navGoals: 'Цели',
    navRecommendations: 'Рекомендации',
    navProfile: 'Профиль',
    navAnalytics: 'Аналитика',
    navWorkouts: 'Тренировки',
    navPhotos: 'Фото',
    navOnboarding: 'Старт',
    navMethodology: 'Методика',
    navAdmin: 'Админ',
    logout: 'Выйти',
    loading: 'Загрузка данных',
    close: 'Закрыть',
    reload: 'Перезагрузить страницу',
    uiStopped: 'Интерфейс остановлен',
    uiStoppedText: 'Мы поймали ошибку, чтобы приложение не показало пустой экран.',
    authSubtitle: 'Вебсервис визуализации физической формы',
    loginTitle: 'Body Vision',
    email: 'Email',
    password: 'Пароль',
    login: 'Войти',
    loggingIn: 'Вход',
    noAccount: 'Нет аккаунта?',
    registerLink: 'Зарегистрироваться',
    registerTitle: 'Регистрация',
    registerSubtitle: 'Создание профиля для расчета прогресса',
    name: 'Имя',
    gender: 'Пол',
    male: 'Мужской',
    female: 'Женский',
    other: 'Другой',
    age: 'Возраст',
    height: 'Рост',
    currentWeight: 'Текущий вес',
    activity: 'Активность',
    sedentary: 'Минимальная',
    light: 'Легкая',
    moderate: 'Средняя',
    active: 'Высокая',
    veryActive: 'Очень высокая',
    createAccount: 'Создать аккаунт',
    creating: 'Создание',
    alreadyAccount: 'Уже есть аккаунт?',
    loginSuccess: 'Вход выполнен. Добро пожаловать в Body Vision.',
    registerSuccess: 'Аккаунт создан. Можно заполнять первые замеры.',
    dashboardKicker: 'Обзор',
    dashboardTitle: 'Dashboard физической формы',
    goalPercent: 'цели',
    needDataTitle: 'Нужны замер и активная цель',
    needDataText: 'Добавь первый замер и цель, чтобы dashboard начал показывать точный прогресс, разницу и персональные рекомендации.',
    serverDataError: 'Не удалось загрузить данные. Проверь подключение к серверу.',
    weight: 'Вес',
    bodyFat: 'Процент жира',
    waist: 'Талия',
    target: 'Цель',
    difference: 'Разница',
    noData: 'Нет данных',
    basalMetabolism: 'Базовый обмен',
    maintenanceCalories: 'Норма калорий',
    withActivity: 'С учетом активности',
    recommendation: 'Рекомендация',
    forGoal: 'Для выбранной цели',
    daysToGoal: 'Дней до цели',
    tempo: 'Темп',
    notEnoughHistoryTitle: 'Недостаточно истории',
    notEnoughHistoryText: 'Графики появятся после добавления нескольких замеров.',
    bodyModel: 'SVG модель',
    bodyCompare: 'Сравнение формы',
    demoSilhouette: 'Демо-силуэт',
    currentShape: 'Текущая форма',
    desiredShape: 'Желаемая форма',
    bodyPlaceholder: 'Заполните данные для точного силуэта',
    history: 'История',
    weightChart: 'Вес',
    compositionChart: 'Жир и талия',
    measurementsTitle: 'Замеры тела',
    newMeasurement: 'Новый замер',
    edit: 'Редактировать',
    delete: 'Удалить',
    add: 'Добавление',
    editing: 'Редактирование',
    bodyParams: 'Параметры тела',
    measurementDate: 'Дата замера',
    notes: 'Комментарий',
    chest: 'Грудь',
    hips: 'Бедра',
    shoulders: 'Плечи',
    arm: 'Рука',
    thigh: 'Бедро',
    save: 'Сохранить',
    saving: 'Сохранение',
    cancel: 'Отмена',
    measurementsEmptyTitle: 'Замеров пока нет',
    measurementsEmptyText: 'Добавь первый замер, чтобы система начала строить историю прогресса.',
    measurementCreated: 'Новый замер добавлен',
    measurementUpdated: 'Замер обновлен',
    measurementDeleted: 'Замер удален',
    targetShape: 'Целевая форма',
    goalsTitle: 'Цели пользователя',
    activeGoal: 'Активная цель',
    newGoal: 'Новая цель',
    goalParams: 'Параметры цели',
    desiredWeight: 'Желаемый вес',
    desiredBodyFat: 'Желаемый жир',
    desiredWaist: 'Желаемая талия',
    desiredChest: 'Желаемая грудь',
    desiredHips: 'Желаемые бедра',
    targetDate: 'Дата цели',
    goalType: 'Тип цели',
    weightLoss: 'Похудение',
    muscleGain: 'Набор массы',
    maintenance: 'Поддержание',
    saveGoal: 'Сохранить цель',
    goalsEmptyTitle: 'Цель еще не создана',
    goalsEmptyText: 'Заполни параметры желаемой формы, чтобы включить расчеты прогресса.',
    goalCreated: 'Цель создана',
    goalUpdated: 'Цель обновлена',
    goalDeleted: 'Цель удалена',
    until: 'До',
    recommendationsTitle: 'Рекомендации',
    calculations: 'Расчеты',
    goalLooksRealistic: 'Цель выглядит реалистично по текущим данным.',
    recWeightLoss: 'Используй умеренный дефицит калорий и достаточное количество белка, чтобы сохранить мышечную массу.',
    recMuscleGain: 'Используй контролируемый профицит калорий и прогрессивные силовые тренировки.',
    recMaintenance: 'Держи калории около нормы поддержания и обновляй замеры каждые 1-2 недели.',
    recUpdateMeasurements: 'Регулярно обновляй замеры тела, чтобы графики прогресса были точнее.',
    warningWeightLoss: 'Цель может быть слишком агрессивной: обычно рекомендуется снижение веса до 0.5-1 кг в неделю.',
    warningMuscleGain: 'Цель может быть слишком агрессивной: реалистичный набор мышечной массы обычно медленнее 0.5 кг в неделю.',
    leftDays: 'осталось',
    days: 'дней',
    profileTitle: 'Данные пользователя',
    profileKicker: 'Профиль',
    profileUpdated: 'Профиль обновлен',
    createdAt: 'Создан',
    saveProfile: 'Сохранить профиль',
    kg: 'кг',
    cm: 'см',
    kcal: 'ккал',
    perWeek: 'кг/нед',
    chartFat: 'Жир',
    period_week: '7 дней',
    period_month: 'Месяц',
    period_all: 'Все',
    analyticsKicker: 'Отчет',
    analyticsTitle: 'Аналитика прогресса',
    exportPdf: 'Экспорт PDF',
    weightChange: 'Изменение веса',
    waistChange: 'Изменение талии',
    fatChange: 'Изменение жира',
    selectedPeriod: 'Выбранный период',
    trendDown: 'Снижение',
    trendUp: 'Рост',
    entries: 'Записи',
    reportInsightWeight: 'Тренд веса рассчитан от первого до последнего замера выбранного периода.',
    reportInsightCalendar: 'Этот блок можно распечатать как недельный или месячный отчет.',
    analyticsEmptyTitle: 'Недостаточно данных',
    analyticsEmptyText: 'Добавь минимум два замера, чтобы построить отчет.',
    calendarKicker: 'Календарь',
    calendarTitle: 'Календарь замеров',
    photoKicker: 'Фото-прогресс',
    photoTitle: 'Фото прогресса',
    selectPhoto: 'Выберите фото',
    photoReady: 'Фото выбрано',
    addPhoto: 'Добавить фото',
    photoAdded: 'Фото добавлено',
    photoDeleted: 'Фото удалено',
    photoTooLarge: 'Фото слишком большое',
    photoEmptyTitle: 'Фото пока нет',
    photoEmptyText: 'Добавь фото прогресса, чтобы сравнивать визуальные изменения.',
    methodKicker: 'Методика',
    methodTitle: 'Методика расчетов',
    progressMethod: 'Прогресс',
    adminKicker: 'Администрирование',
    adminTitle: 'Админ-панель',
    adminDenied: 'Нужен доступ администратора',
    users: 'Пользователи'
    ,
    workoutKicker: 'План',
    workoutTitle: 'План тренировок',
    workoutName: 'Название тренировки',
    dayOfWeek: 'День недели',
    workoutType: 'Тип тренировки',
    exercises: 'Упражнения',
    createWorkout: 'Создать тренировку',
    workoutCreated: 'Тренировка создана',
    workoutDeleted: 'Тренировка удалена',
    workoutEmptyTitle: 'Тренировок пока нет',
    workoutEmptyText: 'Создай недельный план, связанный с целью физической формы.',
    complete: 'Отметить выполнение',
    monday: 'Понедельник',
    tuesday: 'Вторник',
    wednesday: 'Среда',
    thursday: 'Четверг',
    friday: 'Пятница',
    saturday: 'Суббота',
    sunday: 'Воскресенье',
    strength: 'Силовая',
    cardio: 'Кардио',
    mobility: 'Мобилити',
    recovery: 'Восстановление',
    onboardingKicker: 'Старт',
    onboardingTitle: 'Пошаговая настройка',
    onboardingMeasurements: 'Добавь первый замер',
    onboardingMeasurementsText: 'Заполни вес, талию, процент жира и другие параметры.',
    onboardingGoals: 'Создай цель',
    onboardingGoalsText: 'Укажи желаемую форму и дату достижения.',
    onboardingPhotos: 'Добавь фото',
    onboardingPhotosText: 'Сохрани визуальную точку старта для сравнения.',
    onboardingAnalytics: 'Открой аналитику',
    onboardingAnalyticsText: 'Проверь прогноз, план-факт и стабильность прогресса.',
    openStep: 'Открыть шаг',
    forecastToGoal: 'Прогноз до цели',
    basedOnTrend: 'По текущему тренду',
    planVsFact: 'План vs факт',
    aheadOfPlan: 'По плану',
    behindPlan: 'Отставание',
    stability: 'Стабильность',
    stabilityText: 'Меньше скачков лучше',
    targetDaysLeft: 'Дней до даты цели'
  },
  uk: {
    appSubtitle: 'Fitness MVP',
    navDashboard: 'Dashboard',
    navMeasurements: 'Заміри',
    navGoals: 'Цілі',
    navRecommendations: 'Рекомендації',
    navProfile: 'Профіль',
    navAnalytics: 'Аналітика',
    navWorkouts: 'Тренування',
    navPhotos: 'Фото',
    navOnboarding: 'Старт',
    navMethodology: 'Методика',
    navAdmin: 'Адмін',
    logout: 'Вийти',
    loading: 'Завантаження даних',
    close: 'Закрити',
    reload: 'Перезавантажити сторінку',
    uiStopped: 'Інтерфейс зупинено',
    uiStoppedText: 'Ми перехопили помилку, щоб застосунок не показав порожній екран.',
    authSubtitle: 'Вебсервіс візуалізації фізичної форми',
    loginTitle: 'Body Vision',
    email: 'Email',
    password: 'Пароль',
    login: 'Увійти',
    loggingIn: 'Вхід',
    noAccount: 'Немає акаунта?',
    registerLink: 'Зареєструватися',
    registerTitle: 'Реєстрація',
    registerSubtitle: 'Створення профілю для розрахунку прогресу',
    name: "Ім'я",
    gender: 'Стать',
    male: 'Чоловіча',
    female: 'Жіноча',
    other: 'Інша',
    age: 'Вік',
    height: 'Зріст',
    currentWeight: 'Поточна вага',
    activity: 'Активність',
    sedentary: 'Мінімальна',
    light: 'Легка',
    moderate: 'Середня',
    active: 'Висока',
    veryActive: 'Дуже висока',
    createAccount: 'Створити акаунт',
    creating: 'Створення',
    alreadyAccount: 'Вже маєте акаунт?',
    loginSuccess: 'Вхід виконано. Ласкаво просимо до Body Vision.',
    registerSuccess: 'Акаунт створено. Можна додавати перші заміри.',
    dashboardKicker: 'Огляд',
    dashboardTitle: 'Dashboard фізичної форми',
    goalPercent: 'цілі',
    needDataTitle: 'Потрібні замір і активна ціль',
    needDataText: 'Додайте перший замір і ціль, щоб dashboard показував точний прогрес, різницю та персональні рекомендації.',
    serverDataError: "Не вдалося завантажити дані. Перевірте підключення до сервера.",
    weight: 'Вага',
    bodyFat: 'Відсоток жиру',
    waist: 'Талія',
    target: 'Ціль',
    difference: 'Різниця',
    noData: 'Немає даних',
    basalMetabolism: 'Базовий обмін',
    maintenanceCalories: 'Норма калорій',
    withActivity: 'З урахуванням активності',
    recommendation: 'Рекомендація',
    forGoal: 'Для обраної цілі',
    daysToGoal: 'Днів до цілі',
    tempo: 'Темп',
    notEnoughHistoryTitle: 'Недостатньо історії',
    notEnoughHistoryText: 'Графіки зʼявляться після додавання кількох замірів.',
    bodyModel: 'SVG модель',
    bodyCompare: 'Порівняння форми',
    demoSilhouette: 'Демо-силует',
    currentShape: 'Поточна форма',
    desiredShape: 'Бажана форма',
    bodyPlaceholder: 'Заповніть дані для точного силуету',
    history: 'Історія',
    weightChart: 'Вага',
    compositionChart: 'Жир і талія',
    measurementsTitle: 'Заміри тіла',
    newMeasurement: 'Новий замір',
    edit: 'Редагувати',
    delete: 'Видалити',
    add: 'Додавання',
    editing: 'Редагування',
    bodyParams: 'Параметри тіла',
    measurementDate: 'Дата заміру',
    notes: 'Коментар',
    chest: 'Груди',
    hips: 'Стегна',
    shoulders: 'Плечі',
    arm: 'Рука',
    thigh: 'Стегно',
    save: 'Зберегти',
    saving: 'Збереження',
    cancel: 'Скасувати',
    measurementsEmptyTitle: 'Замірів поки немає',
    measurementsEmptyText: 'Додайте перший замір, щоб система почала будувати історію прогресу.',
    measurementCreated: 'Новий замір додано',
    measurementUpdated: 'Замір оновлено',
    measurementDeleted: 'Замір видалено',
    targetShape: 'Цільова форма',
    goalsTitle: 'Цілі користувача',
    activeGoal: 'Активна ціль',
    newGoal: 'Нова ціль',
    goalParams: 'Параметри цілі',
    desiredWeight: 'Бажана вага',
    desiredBodyFat: 'Бажаний жир',
    desiredWaist: 'Бажана талія',
    desiredChest: 'Бажані груди',
    desiredHips: 'Бажані стегна',
    targetDate: 'Дата цілі',
    goalType: 'Тип цілі',
    weightLoss: 'Схуднення',
    muscleGain: 'Набір маси',
    maintenance: 'Підтримання',
    saveGoal: 'Зберегти ціль',
    goalsEmptyTitle: 'Ціль ще не створена',
    goalsEmptyText: 'Заповніть параметри бажаної форми, щоб увімкнути розрахунки прогресу.',
    goalCreated: 'Ціль створено',
    goalUpdated: 'Ціль оновлено',
    goalDeleted: 'Ціль видалено',
    until: 'До',
    recommendationsTitle: 'Рекомендації',
    calculations: 'Розрахунки',
    goalLooksRealistic: 'Ціль виглядає реалістично за поточними даними.',
    recWeightLoss: 'Використовуйте помірний дефіцит калорій і достатню кількість білка, щоб зберегти мʼязову масу.',
    recMuscleGain: 'Використовуйте контрольований профіцит калорій і прогресивні силові тренування.',
    recMaintenance: 'Тримайте калорії біля норми підтримання та оновлюйте заміри кожні 1-2 тижні.',
    recUpdateMeasurements: 'Регулярно оновлюйте заміри тіла, щоб графіки прогресу були точнішими.',
    warningWeightLoss: 'Ціль може бути занадто агресивною: зазвичай рекомендується зниження ваги до 0.5-1 кг на тиждень.',
    warningMuscleGain: 'Ціль може бути занадто агресивною: реалістичний набір мʼязової маси зазвичай повільніший за 0.5 кг на тиждень.',
    leftDays: 'залишилось',
    days: 'днів',
    profileTitle: 'Дані користувача',
    profileKicker: 'Профіль',
    profileUpdated: 'Профіль оновлено',
    createdAt: 'Створено',
    saveProfile: 'Зберегти профіль',
    kg: 'кг',
    cm: 'см',
    kcal: 'ккал',
    perWeek: 'кг/тиж',
    chartFat: 'Жир',
    period_week: '7 днів',
    period_month: 'Місяць',
    period_all: 'Усе',
    analyticsKicker: 'Звіт',
    analyticsTitle: 'Аналітика прогресу',
    exportPdf: 'Експорт PDF',
    weightChange: 'Зміна ваги',
    waistChange: 'Зміна талії',
    fatChange: 'Зміна жиру',
    selectedPeriod: 'Обраний період',
    trendDown: 'Зниження',
    trendUp: 'Зростання',
    entries: 'Записи',
    reportInsightWeight: 'Тренд ваги розраховано від першого до останнього заміру обраного періоду.',
    reportInsightCalendar: 'Цей блок можна роздрукувати як тижневий або місячний звіт.',
    analyticsEmptyTitle: 'Недостатньо даних',
    analyticsEmptyText: 'Додайте мінімум два заміри, щоб побудувати звіт.',
    calendarKicker: 'Календар',
    calendarTitle: 'Календар замірів',
    photoKicker: 'Фото-прогрес',
    photoTitle: 'Фото прогресу',
    selectPhoto: 'Оберіть фото',
    photoReady: 'Фото обрано',
    addPhoto: 'Додати фото',
    photoAdded: 'Фото додано',
    photoDeleted: 'Фото видалено',
    photoTooLarge: 'Фото занадто велике',
    photoEmptyTitle: 'Фото поки немає',
    photoEmptyText: 'Додайте фото прогресу, щоб порівнювати візуальні зміни.',
    methodKicker: 'Методика',
    methodTitle: 'Методика розрахунків',
    progressMethod: 'Прогрес',
    adminKicker: 'Адміністрування',
    adminTitle: 'Адмін-панель',
    adminDenied: 'Потрібен доступ адміністратора',
    users: 'Користувачі'
    ,
    workoutKicker: 'План',
    workoutTitle: 'План тренувань',
    workoutName: 'Назва тренування',
    dayOfWeek: 'День тижня',
    workoutType: 'Тип тренування',
    exercises: 'Вправи',
    createWorkout: 'Створити тренування',
    workoutCreated: 'Тренування створено',
    workoutDeleted: 'Тренування видалено',
    workoutEmptyTitle: 'Тренувань поки немає',
    workoutEmptyText: 'Створи тижневий план, повʼязаний із ціллю фізичної форми.',
    complete: 'Позначити виконання',
    monday: 'Понеділок',
    tuesday: 'Вівторок',
    wednesday: 'Середа',
    thursday: 'Четвер',
    friday: 'Пʼятниця',
    saturday: 'Субота',
    sunday: 'Неділя',
    strength: 'Силове',
    cardio: 'Кардіо',
    mobility: 'Мобіліті',
    recovery: 'Відновлення',
    onboardingKicker: 'Старт',
    onboardingTitle: 'Покрокове налаштування',
    onboardingMeasurements: 'Додай перший замір',
    onboardingMeasurementsText: 'Заповни вагу, талію, відсоток жиру та інші параметри.',
    onboardingGoals: 'Створи ціль',
    onboardingGoalsText: 'Вкажи бажану форму та дату досягнення.',
    onboardingPhotos: 'Додай фото',
    onboardingPhotosText: 'Збережи візуальну стартову точку для порівняння.',
    onboardingAnalytics: 'Відкрий аналітику',
    onboardingAnalyticsText: 'Перевір прогноз, план-факт і стабільність прогресу.',
    openStep: 'Відкрити крок',
    forecastToGoal: 'Прогноз до цілі',
    basedOnTrend: 'За поточним трендом',
    planVsFact: 'План vs факт',
    aheadOfPlan: 'За планом',
    behindPlan: 'Відставання',
    stability: 'Стабільність',
    stabilityText: 'Менше стрибків краще',
    targetDaysLeft: 'Днів до дати цілі'
  },
  en: {
    appSubtitle: 'Fitness MVP',
    navDashboard: 'Dashboard',
    navMeasurements: 'Measurements',
    navGoals: 'Goals',
    navRecommendations: 'Recommendations',
    navProfile: 'Profile',
    navAnalytics: 'Analytics',
    navWorkouts: 'Workouts',
    navPhotos: 'Photos',
    navOnboarding: 'Start',
    navMethodology: 'Method',
    navAdmin: 'Admin',
    logout: 'Log out',
    loading: 'Loading data',
    close: 'Close',
    reload: 'Reload page',
    uiStopped: 'Interface stopped',
    uiStoppedText: 'An error was caught so the app does not show a blank screen.',
    authSubtitle: 'Body shape visualization web service',
    loginTitle: 'Body Vision',
    email: 'Email',
    password: 'Password',
    login: 'Sign in',
    loggingIn: 'Signing in',
    noAccount: 'No account?',
    registerLink: 'Create one',
    registerTitle: 'Registration',
    registerSubtitle: 'Create a profile to calculate progress',
    name: 'Name',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    age: 'Age',
    height: 'Height',
    currentWeight: 'Current weight',
    activity: 'Activity',
    sedentary: 'Sedentary',
    light: 'Light',
    moderate: 'Moderate',
    active: 'Active',
    veryActive: 'Very active',
    createAccount: 'Create account',
    creating: 'Creating',
    alreadyAccount: 'Already have an account?',
    loginSuccess: 'Signed in. Welcome to Body Vision.',
    registerSuccess: 'Account created. You can add your first measurements.',
    dashboardKicker: 'Overview',
    dashboardTitle: 'Body shape dashboard',
    goalPercent: 'of goal',
    needDataTitle: 'Measurement and active goal required',
    needDataText: 'Add your first measurement and goal so the dashboard can show accurate progress, differences and recommendations.',
    serverDataError: 'Could not load data. Check the server connection.',
    weight: 'Weight',
    bodyFat: 'Body fat',
    waist: 'Waist',
    target: 'Target',
    difference: 'Difference',
    noData: 'No data',
    basalMetabolism: 'Basal metabolism',
    maintenanceCalories: 'Maintenance calories',
    withActivity: 'With activity factor',
    recommendation: 'Recommendation',
    forGoal: 'For selected goal',
    daysToGoal: 'Days to goal',
    tempo: 'Pace',
    notEnoughHistoryTitle: 'Not enough history',
    notEnoughHistoryText: 'Charts will appear after several measurements are added.',
    bodyModel: 'SVG model',
    bodyCompare: 'Shape comparison',
    demoSilhouette: 'Demo silhouette',
    currentShape: 'Current shape',
    desiredShape: 'Desired shape',
    bodyPlaceholder: 'Fill in data for a precise silhouette',
    history: 'History',
    weightChart: 'Weight',
    compositionChart: 'Fat and waist',
    measurementsTitle: 'Body measurements',
    newMeasurement: 'New measurement',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Adding',
    editing: 'Editing',
    bodyParams: 'Body parameters',
    measurementDate: 'Measurement date',
    notes: 'Comment',
    chest: 'Chest',
    hips: 'Hips',
    shoulders: 'Shoulders',
    arm: 'Arm',
    thigh: 'Thigh',
    save: 'Save',
    saving: 'Saving',
    cancel: 'Cancel',
    measurementsEmptyTitle: 'No measurements yet',
    measurementsEmptyText: 'Add your first measurement so the system can build a progress history.',
    measurementCreated: 'New measurement added',
    measurementUpdated: 'Measurement updated',
    measurementDeleted: 'Measurement deleted',
    targetShape: 'Target shape',
    goalsTitle: 'User goals',
    activeGoal: 'Active goal',
    newGoal: 'New goal',
    goalParams: 'Goal parameters',
    desiredWeight: 'Desired weight',
    desiredBodyFat: 'Desired body fat',
    desiredWaist: 'Desired waist',
    desiredChest: 'Desired chest',
    desiredHips: 'Desired hips',
    targetDate: 'Target date',
    goalType: 'Goal type',
    weightLoss: 'Weight loss',
    muscleGain: 'Muscle gain',
    maintenance: 'Maintenance',
    saveGoal: 'Save goal',
    goalsEmptyTitle: 'No goal created yet',
    goalsEmptyText: 'Fill in desired shape parameters to enable progress calculations.',
    goalCreated: 'Goal created',
    goalUpdated: 'Goal updated',
    goalDeleted: 'Goal deleted',
    until: 'Until',
    recommendationsTitle: 'Recommendations',
    calculations: 'Calculations',
    goalLooksRealistic: 'The goal looks realistic based on current data.',
    recWeightLoss: 'Use a moderate calorie deficit and keep protein intake high enough to preserve muscle mass.',
    recMuscleGain: 'Use a controlled calorie surplus and progressive strength training.',
    recMaintenance: 'Keep calories near maintenance and monitor measurements every 1-2 weeks.',
    recUpdateMeasurements: 'Update body measurements regularly to make the progress charts more accurate.',
    warningWeightLoss: 'Goal may be too aggressive: recommended weight loss is usually up to 0.5-1 kg per week.',
    warningMuscleGain: 'Goal may be too aggressive: realistic muscle gain is usually slower than 0.5 kg per week.',
    leftDays: 'left',
    days: 'days',
    profileTitle: 'User data',
    profileKicker: 'Profile',
    profileUpdated: 'Profile updated',
    createdAt: 'Created',
    saveProfile: 'Save profile',
    kg: 'kg',
    cm: 'cm',
    kcal: 'kcal',
    perWeek: 'kg/week',
    chartFat: 'Fat',
    period_week: '7 days',
    period_month: 'Month',
    period_all: 'All',
    analyticsKicker: 'Report',
    analyticsTitle: 'Progress analytics',
    exportPdf: 'Export PDF',
    weightChange: 'Weight change',
    waistChange: 'Waist change',
    fatChange: 'Fat change',
    selectedPeriod: 'Selected period',
    trendDown: 'Decreasing',
    trendUp: 'Increasing',
    entries: 'Entries',
    reportInsightWeight: 'Weight trend is calculated from the first and latest selected measurement.',
    reportInsightCalendar: 'This section can be printed as a weekly or monthly report.',
    analyticsEmptyTitle: 'Not enough data',
    analyticsEmptyText: 'Add at least two measurements to build a report.',
    calendarKicker: 'Calendar',
    calendarTitle: 'Measurement calendar',
    photoKicker: 'Progress photos',
    photoTitle: 'Photo progress',
    selectPhoto: 'Select photo',
    photoReady: 'Photo selected',
    addPhoto: 'Add photo',
    photoAdded: 'Photo added',
    photoDeleted: 'Photo deleted',
    photoTooLarge: 'Photo is too large',
    photoEmptyTitle: 'No photos yet',
    photoEmptyText: 'Add progress photos to compare visual changes over time.',
    methodKicker: 'Methodology',
    methodTitle: 'Calculation methodology',
    progressMethod: 'Progress',
    adminKicker: 'Administration',
    adminTitle: 'Admin panel',
    adminDenied: 'Admin access required',
    users: 'Users'
    ,
    workoutKicker: 'Plan',
    workoutTitle: 'Workout plan',
    workoutName: 'Workout name',
    dayOfWeek: 'Day of week',
    workoutType: 'Workout type',
    exercises: 'Exercises',
    createWorkout: 'Create workout',
    workoutCreated: 'Workout created',
    workoutDeleted: 'Workout deleted',
    workoutEmptyTitle: 'No workouts yet',
    workoutEmptyText: 'Create a weekly plan connected to your body goal.',
    complete: 'Mark completed',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    strength: 'Strength',
    cardio: 'Cardio',
    mobility: 'Mobility',
    recovery: 'Recovery',
    onboardingKicker: 'Start',
    onboardingTitle: 'Setup guide',
    onboardingMeasurements: 'Add first measurement',
    onboardingMeasurementsText: 'Fill in weight, waist, body fat and other parameters.',
    onboardingGoals: 'Create a goal',
    onboardingGoalsText: 'Set desired shape and target date.',
    onboardingPhotos: 'Add photos',
    onboardingPhotosText: 'Save a visual starting point for comparison.',
    onboardingAnalytics: 'Open analytics',
    onboardingAnalyticsText: 'Check forecast, plan vs fact and progress stability.',
    openStep: 'Open step',
    forecastToGoal: 'Forecast to goal',
    basedOnTrend: 'Based on current trend',
    planVsFact: 'Plan vs fact',
    aheadOfPlan: 'On track',
    behindPlan: 'Behind plan',
    stability: 'Stability',
    stabilityText: 'Lower volatility is better',
    targetDaysLeft: 'Target days left'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('bodyVisionLanguage') || 'ru');

  const changeLanguage = (nextLanguage) => {
    setLanguage(nextLanguage);
    localStorage.setItem('bodyVisionLanguage', nextLanguage);
  };

  const t = (key) => translations[language]?.[key] || translations.ru[key] || key;

  const value = useMemo(() => ({
    language,
    setLanguage: changeLanguage,
    t
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
